<a href="https://colab.research.google.com/github/soonho123/2026-1-BDA-my-code/blob/main/04w_array_stack_split_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#배열결합



In [2]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
b = np.arange(6, 12).reshape(3, 2)
b


array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a, b))

In [4]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

#hstack()


In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

In [ ]:
b = np.arange(10, 19).reshape(3, 3)
b

In [ ]:
np.hstack((a, b))

In [ ]:
c = np.array([[10, 20], [30, 40]])
c

#np.column_stack((a,b))

In [6]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [7]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [8]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [9]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [10]:
np.column_stack == np.hstack

False

#np.row_stack()

In [11]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [13]:
np.row_stack((a, b))

/tmp/ipykernel_19801/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

#concatenate

In [14]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [15]:
np.concatenate((a, b, c))



array([1, 2, 3, 4, 5, 6])

In [16]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [17]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

#concatenate2차원결합

In [18]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [20]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [21]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [22]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [23]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [24]:
# 평면화 작업 후 연결
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

#np.stack

In [25]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [26]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [27]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

#배열

In [30]:
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [31]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [32]:

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [34]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [35]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [64]:
ax0.shape

(3, 2, 3)

#npc

In [65]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [66]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [69]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [70]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [71]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [72]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

#npr

In [73]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [74]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [75]:
np.hstack((a, b))


array([1, 2, 3, 4, 5, 6])

In [76]:
np.row_stack((a, b))

/tmp/ipykernel_19801/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [78]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [79]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [80]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [81]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [83]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [84]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [85]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [86]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [87]:
np.r_['0, 2', [1,2,3], [4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
np.r_['0, 3', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

#np.split()

In [89]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [90]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [91]:
import numpy as np
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [92]:
np.split(y, [2, 3, 4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [93]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [94]:
x= np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.split(x, [2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

## 다차원 배열 np.hsplit(ary, n)

In [96]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [97]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [98]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [99]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [100]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [101]:
np.split(b, 3, axis=0)

[array([4]), array([5]), array([6])]

In [102]:
np.split(b, [2, 4, 6], axis=0)

[array([4, 5]), array([6]), array([], dtype=int64), array([], dtype=int64)]

#np.hsplit

In [103]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [105]:

np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [106]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [107]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [108]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [109]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

##np.vsplit

In [110]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [111]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [112]:
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [113]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [114]:
a[:1, :]


array([[0, 1, 2]])

In [115]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [116]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

## 3차원 배열의 hsplit()


In [117]:
np.array_split(x, 2, axis=0)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]

In [118]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [119]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [120]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [121]:
import numpy as np
rg = np.random.default_rng(1)
rg.random()
#난수 초기값 (0,1) 실수 난수

0.5118216247002567

In [122]:
rg.random()

0.9504636963259353

In [123]:
rg.random((3,4)) #괄호2개 필수

array([[0.14415961, 0.94864945, 0.31183145, 0.42332645],
       [0.82770259, 0.40919914, 0.54959369, 0.02755911],
       [0.75351311, 0.53814331, 0.32973172, 0.7884287 ]])

In [124]:
rg.random((3,4,5))

array([[[0.30319483, 0.45349789, 0.1340417 , 0.40311299, 0.20345524],
        [0.26231334, 0.75036467, 0.28040876, 0.48519097, 0.9807372 ],
        [0.96165719, 0.72478994, 0.54122686, 0.2768912 , 0.16065201],
        [0.96992541, 0.51606859, 0.11586561, 0.62348976, 0.77668311]],

       [[0.6130033 , 0.9172977 , 0.03959288, 0.52858926, 0.45933588],
        [0.06234958, 0.64132817, 0.85263284, 0.59294102, 0.26009745],
        [0.83988152, 0.50949588, 0.51088888, 0.75303021, 0.14792204],
        [0.81962672, 0.68328691, 0.78709694, 0.19161626, 0.80236416]],

       [[0.19132393, 0.08155262, 0.85522697, 0.8612835 , 0.8765371 ],
        [0.47190972, 0.27404839, 0.00709183, 0.6457209 , 0.71990938],
        [0.83556922, 0.28187783, 0.21521817, 0.63933138, 0.80505483],
        [0.96367087, 0.15052483, 0.48221239, 0.89471586, 0.42271691]]])

In [125]:
import numpy as np
rg = np.random.default_rng(12)
rg.integers(1,7,(3,4))#[1,7] 정수 난수


array([[4, 2, 6, 6],
       [1, 2, 2, 2],
       [4, 3, 3, 2]])

In [126]:
rg.integers(low=1, high=10,size=(2,8)) ## 정수 난수 [1,10]

array([[9, 7, 6, 2, 2, 9, 3, 8],
       [8, 1, 5, 5, 5, 1, 7, 3]])

In [127]:
import numpy as np
rg = np.random.default_rng(12)
rg.standard_normal(10) ## 표준 정규 분포 실수 난수/

array([-0.00682678,  1.04614329,  0.74158842,  0.72395654,  1.61877622,
       -1.20555814, -0.62695547, -1.32066321, -0.10775251,  0.99876366])

In [128]:
rg.standard_normal((3,4))

array([[-0.02194789,  0.49588007, -1.91076866,  0.14706417],
       [-0.90694325,  1.77538939,  0.88684908,  0.94934948],
       [-0.05785496,  0.61286227,  0.65789016, -0.34440267]])

In [129]:
rg.standard_normal((10,5))

array([[-4.97372035e-01, -1.14772783e-01, -6.05452009e-01,
        -5.94339418e-01, -2.83375376e-01],
       [-7.28417727e-01,  7.66327786e-01, -1.59608633e+00,
         8.23562129e-01, -6.25566470e-01],
       [-5.45939956e-01, -1.35084714e+00, -1.44242119e-01,
        -2.47661509e-01,  1.91455831e-01],
       [-5.33774296e-01,  9.37561793e-02,  1.81969184e+00,
         4.08999694e-01, -5.73690037e-01],
       [ 9.53109595e-01, -1.28801134e-01,  5.93874468e-01,
         6.12747429e-01, -3.91065717e-01],
       [-1.93028750e+00, -3.47653623e-01,  5.51455424e-01,
        -3.80110407e-01,  4.38969315e-01],
       [ 9.79540372e-01, -5.44113415e-01,  1.23135175e+00,
         1.62180446e+00,  1.07904594e+00],
       [ 1.16546284e+00,  1.09679645e+00,  2.25453906e+00,
         1.85860905e-01,  2.08408285e-03],
       [ 6.03107305e-01, -9.08195119e-01, -1.55317676e+00,
        -8.82007973e-01,  3.72565350e-01],
       [ 4.73053341e-01, -1.53635872e+00, -1.88346371e+00,
        -3.16142243e-01

In [130]:
import numpy as np
##np.random.seed(12)
np.random.random()

0.35197380219809493

In [131]:
import numpy as np
np.random.randint(1, 10 ,5)

array([8, 7, 7, 3, 7])

In [132]:
np.random.rand(3,4)

array([[0.28359802, 0.20885356, 0.80377325, 0.02192424],
       [0.75037269, 0.94982563, 0.31842343, 0.18065205],
       [0.17060496, 0.51530074, 0.76145124, 0.43046115]])

In [133]:
np.random.rand(5,3)

array([[0.57182011, 0.73763528, 0.39410104],
       [0.89189775, 0.04562934, 0.90230512],
       [0.20469242, 0.7775932 , 0.24211247],
       [0.21488228, 0.38491895, 0.00315298],
       [0.01142421, 0.22406269, 0.85028523]])