<a href="https://colab.research.google.com/github/soonho123/2026-1-BDA-my-code/blob/main/04w_array_stack_split_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#배열결합



In [1]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [4]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [5]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x[:,np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [6]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [7]:
np.column_stack == np.stack

False

In [8]:
import numpy as np
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [11]:
import numpy as np
a = np.arange(1,13).reshape(3,4)
c = np.arange(1,6,2)
a,c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 3, 5]))

In [12]:
c[:,None]

array([[1],
       [3],
       [5]])

In [13]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [14]:
cc = np.expand_dims(c,axis = 1)

array([[1],
       [3],
       [5]])

In [15]:
np.hstack(a, )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [18]:
a = np.arange(1,4)
b = np.arange(4,7)
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [19]:
np.c_[a,b], np.column_stack((a, b))

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [22]:
x = np.arange(1,4).reshape(1,3)
y = np.arange(4,7).reshape(1,3)
x,y

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [23]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [24]:
np.column_stack((x,10,20,y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

###난수 기초와 생성


In [26]:
import numpy as np
rg = np.random.default_rng(1)
rg.random()
#난수 초기값 (0,1) 실수 난수

0.5118216247002567

In [27]:
rg.random()

0.9504636963259353

In [28]:
rg.random((3,4)) #괄호2개 필수

array([[0.14415961, 0.94864945, 0.31183145, 0.42332645],
       [0.82770259, 0.40919914, 0.54959369, 0.02755911],
       [0.75351311, 0.53814331, 0.32973172, 0.7884287 ]])

In [30]:
rg.random((3,4,5))

array([[[0.58950206, 0.02449068, 0.67345989, 0.91908862, 0.82682533],
        [0.88552027, 0.66035538, 0.24555227, 0.768517  , 0.21167474],
        [0.83127483, 0.06271792, 0.82548781, 0.16450727, 0.375147  ],
        [0.31673817, 0.69133704, 0.17857188, 0.39625616, 0.0058246 ]],

       [[0.26249471, 0.42118881, 0.10592124, 0.63315995, 0.38042427],
        [0.72529394, 0.65386601, 0.43122675, 0.86732051, 0.63213512],
        [0.81027435, 0.34179472, 0.54366929, 0.19629689, 0.99614119],
        [0.24321546, 0.25686747, 0.07319007, 0.25780312, 0.76312853]],

       [[0.69789357, 0.12867321, 0.3762385 , 0.42092139, 0.66498425],
        [0.45592896, 0.58651833, 0.8396846 , 0.72647361, 0.36500726],
        [0.44839631, 0.36769957, 0.10973466, 0.20324154, 0.28380649],
        [0.3141339 , 0.31304786, 0.57669972, 0.97168998, 0.77466413]]])

In [31]:
import numpy as np
rg = np.random.default_rng(12)
rg.integers(1,7,(3,4))#[1,7] 정수 난수


array([[4, 2, 6, 6],
       [1, 2, 2, 2],
       [4, 3, 3, 2]])

In [32]:
rg.integers(low=1, high=10,size=(2,8)) ## 정수 난수 [1,10]

array([[9, 7, 6, 2, 2, 9, 3, 8],
       [8, 1, 5, 5, 5, 1, 7, 3]])

In [33]:
import numpy as np
rg = np.random.default_rng(12)
rg.standard_normal(10) ## 표준 정규 분포 실수 난수/

array([-0.00682678,  1.04614329,  0.74158842,  0.72395654,  1.61877622,
       -1.20555814, -0.62695547, -1.32066321, -0.10775251,  0.99876366])

In [35]:
rg.standard_normal((3,4))

array([[-0.02194789,  0.49588007, -1.91076866,  0.14706417],
       [-0.90694325,  1.77538939,  0.88684908,  0.94934948],
       [-0.05785496,  0.61286227,  0.65789016, -0.34440267]])

In [36]:
rg.standard_normal((10,5))

array([[-4.97372035e-01, -1.14772783e-01, -6.05452009e-01,
        -5.94339418e-01, -2.83375376e-01],
       [-7.28417727e-01,  7.66327786e-01, -1.59608633e+00,
         8.23562129e-01, -6.25566470e-01],
       [-5.45939956e-01, -1.35084714e+00, -1.44242119e-01,
        -2.47661509e-01,  1.91455831e-01],
       [-5.33774296e-01,  9.37561793e-02,  1.81969184e+00,
         4.08999694e-01, -5.73690037e-01],
       [ 9.53109595e-01, -1.28801134e-01,  5.93874468e-01,
         6.12747429e-01, -3.91065717e-01],
       [-1.93028750e+00, -3.47653623e-01,  5.51455424e-01,
        -3.80110407e-01,  4.38969315e-01],
       [ 9.79540372e-01, -5.44113415e-01,  1.23135175e+00,
         1.62180446e+00,  1.07904594e+00],
       [ 1.16546284e+00,  1.09679645e+00,  2.25453906e+00,
         1.85860905e-01,  2.08408285e-03],
       [ 6.03107305e-01, -9.08195119e-01, -1.55317676e+00,
        -8.82007973e-01,  3.72565350e-01],
       [ 4.73053341e-01, -1.53635872e+00, -1.88346371e+00,
        -3.16142243e-01

In [1]:
import numpy as np
##np.random.seed(12)
np.random.random()

0.7388344278329797

In [2]:
import numpy as np
np.random.randint(1, 10 ,5)

array([4, 7, 5, 4, 7])

In [3]:
np.random.rand(3,4)

array([[0.29975879, 0.96691436, 0.40390942, 0.87292914],
       [0.11976964, 0.573637  , 0.67390576, 0.99271792],
       [0.96423324, 0.64881197, 0.62910727, 0.72233193]])

In [4]:
np.random.rand(5,3)

array([[0.54491609, 0.16076349, 0.58772579],
       [0.99128193, 0.89640337, 0.33185126],
       [0.84927385, 0.08681275, 0.13040944],
       [0.56931025, 0.3378606 , 0.17953263],
       [0.93128145, 0.53703796, 0.43794677]])