<a href="https://colab.research.google.com/github/soonho123/2026-1-BDA-my-code/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D_3%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#딥러닝프로그램 3주차

##ndarry


In [1]:
import numpy as np

a = np.ndarray((2, 3))
a

array([[3.54272361e-315, 0.00000000e+000, 3.37446836e-321],
       [2.10966031e-321, 2.04792761e-306, 7.95751304e-312]])

In [2]:
import numpy as np

a = np.ndarray((3, 2), dtype=int)
a

array([[        717055242,                 0],
       [              683,               427],
       [33498240948699137,     1610618569592]])

In [3]:
a = np.ndarray((3, 2), int)
a

array([[      720496216,               0],
       [133166013470816,       720605328],
       [133166013472016, 133165743786192]])

##array

In [9]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [10]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [11]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [12]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [13]:
import numpy as np

unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [14]:
unicode_array = np.array(['가나다라마'*7, '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

###arange

In [15]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [16]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [17]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
np.reshape(a, (3, 5))

ValueError: cannot reshape array of size 12 into shape (3,5)

###linspace()

In [20]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [21]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [22]:
print( (3-2) / (50-1) )

0.02040816326530612


In [23]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [24]:
print( (3-2) / 50 )

0.02


In [25]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [26]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [27]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [28]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [29]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

###numpy.eye()

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [33]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
b = np.eye(3, 4, -1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

###numpy full

In [36]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [37]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [38]:
np.full([2, 3], (1, 2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [39]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [40]:
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [41]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [42]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [43]:
np.empty([2, 3], dtype=int)

array([[4611686018427387904, 4613487458278336102, 4615288898129284300],
       [4616639978017495449, 4617540697942969548, 4618441417868443647]])

##배열과 스칼라 연산

In [44]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [45]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [46]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [47]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [48]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [49]:
b += a
b

array([0.5, 2.5, 4.5, 6.5])

In [50]:
a @ b

np.float64(31.0)

In [51]:
a.dot(b)

np.float64(31.0)

In [52]:
b.dot(a)

np.float64(31.0)

In [53]:
import numpy as np
print(np.matmul(a, b))
print(np.matmul(b, a))

31.0
31.0


##a.sum()

In [54]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [55]:
a.sum()

np.int64(46)

In [56]:
a.sum(axis=0)

array([16, 30])

In [57]:
a.sum(axis=1)

array([30, 13,  3])

In [58]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [59]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [60]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [61]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [64]:
a.cumsum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

##1차원 배열

In [72]:
import numpy as np

a = np.array([1, 4, 9])
np.sqrt(a)

array([1., 2., 3.])

In [73]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [74]:
np.add(a, b)

array([ 3,  6, 11])

In [75]:


np.divide(a, b)

array([0.5, 2. , 4.5])

In [76]:
np.power(a, b)

array([ 1, 16, 81])

In [77]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [78]:

print(a[3])
print(a[-2])

9
64


In [79]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [80]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [81]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [82]:
a[::-2]

array([81, 49, 25,  9,  1])

In [83]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [84]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [85]:
a[2:5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [86]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

##2차원 배열


In [87]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [88]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [89]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [90]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [91]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [92]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [93]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [94]:
a[, 1]

SyntaxError: invalid syntax (3063698125.py, line 1)

In [95]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [96]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [97]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [98]:
a[2, 4]

np.int64(16)

In [99]:
a[2][4]

np.int64(16)

In [100]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [101]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [102]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [103]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [104]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [105]:
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

##3차원 배열


In [107]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [108]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [109]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [110]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [111]:
a[:, 1, 1]

array([ 5, 17])

In [112]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [113]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [114]:
a[1, ..., 1]

array([13, 17, 21])

In [115]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##ndarray.ravel()

In [117]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [118]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

##np.transpose()

In [119]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [121]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [122]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [123]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [124]:
b.T


array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [125]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [126]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [127]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

#np.swapaxes

In [128]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [129]:
y = np.swapaxes(x, 0, 1)
y


array([[7],
       [8],
       [9]])

In [130]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [131]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [132]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [133]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [134]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

##view

In [135]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [136]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [137]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [138]:

org

array([  0,   1, 200,   3,   4])

In [139]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [140]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [141]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [142]:
org

array([0, 1, 2, 3, 4])

In [143]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [144]:
y = x.reshape(2, 3) # view를 반환
y

array([[0, 1, 2],
       [3, 4, 5]])

In [145]:
print(x.base)

None


In [146]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [147]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [148]:
c = z.copy()
print(c.base)

None


##ndarray

In [149]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [150]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [151]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [152]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [153]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

##뷰와 얕은 복사

In [154]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
b = a
b is a

True

In [156]:
print(id(a))
print(id(b))

133165383940496
133165383940496


In [157]:
print(a.base)
print(b.base)

None
None


In [158]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [159]:
c = a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [160]:
print(id(a))
print(id(c))

133165383940496
133165383940208


In [161]:
print(c.base)

None


In [162]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [163]:
print(id(a))
print(id(v))

133165383940496
133165383931184


In [164]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [165]:
v.base


array([[100, 200,   3],
       [  4,   5,   6]])

##브로드캐스팅

In [166]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [167]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [168]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [170]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [171]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [172]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [174]:
np.set_printoptions(precision=2)

In [175]:
x / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [176]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [177]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [178]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [179]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [180]:
x / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [181]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [182]:
y = arange(1, 3)
y

array([1, 2])

In [183]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [184]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

##상수 np.newaxis

In [185]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [186]:
np.newaxis is None

True

In [187]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [188]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [189]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [190]:
a.shape

(4, 1)

In [191]:
from numpy import array

b = array([1, 2, 3])
b

array([1, 2, 3])

In [192]:
b

array([1, 2, 3])

##고급색인

In [193]:

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [195]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [196]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [197]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [198]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

##2차원 색인

In [199]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [200]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [201]:
x[[0]]

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [202]:
x[0, 1]

np.int64(1)

In [203]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [204]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [205]:
x[[0], [1]]

array([1])

In [206]:
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [207]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [208]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [209]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [210]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [211]:

from numpy import array

x[array([0, 2, 4]), array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 