<a href="https://colab.research.google.com/github/soonho123/2026-1-BDA-my-code/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_4%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 04 다차원 배열 결합과 분리

## section 01 배열의 결합

## (1) 배열 결합



### 과학용 컴퓨팅 패키지 numpy 라이브러리


In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
c = np.arange(20, 24).reshape(2, 2)
c

array([[20, 21],
       [22, 23]])

In [ ]:
np.vstack((a, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [ ]:
np.vstack((a, b, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [ ]:
d = np.array([100, 200])
np.vstack((a, d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [ ]:
d = np.array([100, 200, 300])
np.vstack((a, d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
# 연습
np.r_[a, b, c]

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

### hstack()

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
# 연습
np.c_[a, b]

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [ ]:
np.hstack((a, c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [ ]:
# 연습
np.r_[np.arange(3), np.arange(10, 15)]

array([ 0,  1,  2, 10, 11, 12, 13, 14])

### np.column_stack()

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(10, 22).reshape(3, 4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [ ]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [ ]:
# 연습
np.c_[a, b]

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

### np.column_stack(tup), tup: 1차원 배열

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
np.column_stack == np.hstack

False

### np.row_stack()

In [ ]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
a = np.array([4., 2., 1.])
b = np.array([3., 8., 7.])
print(np.row_stack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [ ]:
print(np.vstack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [ ]:
np.row_stack == np.vstack

True

## (3) 배열 결합 연산 concatenate()와 stack()

#### np.concatenate

In [ ]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

## axis : int, optional
- The axis along which the arrays will be joined.
- If axis is None, arrays are flattened before use.  Default is 0.

In [ ]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b, c), axis=0)


array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b, c), axis=None)


array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [ ]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
# 연습
print(np.vstack((x, y)))
print(np.row_stack((x, y)))
print(np.r_[x, y])

[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]


In [ ]:
np.concatenate((x, y, z))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

In [ ]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [ ]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [ ]:
# 연습
print(np.hstack((x, y, z)))
print(np.column_stack((x, y, z)))
print(np.c_[x, y, z])

[[ 0  1  2 10 11 12 20 21]
 [ 3  4  5 13 14 15 22 23]]
[[ 0  1  2 10 11 12 20 21]
 [ 3  4  5 13 14 15 22 23]]
[[ 0  1  2 10 11 12 20 21]
 [ 3  4  5 13 14 15 22 23]]


In [ ]:
# 평면화 작업 후 연결
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

#### np.stack()

https://medium.com/mlpoint/numpy-for-machine-learning-211a3e58b574

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [ ]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a, b), axis=-2)

array([[1, 2, 3],
       [4, 5, 6]])

### 2D -> 3D 쌓기

#### 3D 이해

In [ ]:
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

![image.png](attachment:image.png)

In [ ]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [ ]:
ax0.shape

(3, 2, 3)

In [ ]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [ ]:
ax1.shape

(2, 3, 3)

In [ ]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [ ]:
ax2.shape

(2, 3, 3)

In [ ]:
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [ ]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [ ]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [ ]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

### np.stack()
- 각 배열을 지정한 축에서 확장한 후 지정한 축으로 결합

![image.png](attachment:image.png)

## (2) 배열의 결합 비교

## column_stack()과 hstack()

In [ ]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [ ]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [ ]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
# 연습
np.c_[a, c]

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

### row_stack()과 vstack()

In [ ]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [ ]:
np.row_stack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

### np.c_

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.c_?

Type:        CClass
String form: <numpy.lib.index_tricks.CClass object at 0x000001C7AABDC1A0>
Length:      0
File:        d:\programdata\anaconda3_240601\lib\site-packages\numpy\lib\index_tricks.py
Docstring:  
Translates slice objects to concatenation along the second axis.

This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
useful because of its common occurrence. In particular, arrays will be
stacked along their last axis after being upgraded to at least 2-D with
1's post-pended to the shape (column vectors made out of 1-D arrays).

See Also
--------
column_stack : Stack 1-D arrays as columns into a 2-D array.
r_ : For more detailed documentation.

Examples
--------
>>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
array([[1, 4],
       [2, 5],
       [3, 6]])
>>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
array([[1, 2, 3, ..., 4, 5, 6]])

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [ ]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

### np.r_

In [ ]:
#### 연습
np.r_['1, 2', [1, 2], [[10, 20]]]

array([[ 1,  2, 10, 20]])

In [ ]:
#### 내 연습
np.r_['1, 2', [[1], [2]], [[10], [20]]]

array([[ 1, 10],
       [ 2, 20]])

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [ ]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [ ]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [ ]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

### np.r_['i, j, k', a, b]

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_[a, a, a] # concatenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['0', a, a] # concatenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['-1', a, a] # concatenate along last axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
np.r_['1', a, a] # concatenate along last axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['0, 2', [1,2,3], [4,5,6]] # concatenate along first axis, dim>=2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_['0, 3', [1,2,3], [4,5,6]] # concatenate along first axis, dim>=3

array([[[1, 2, 3]],

       [[4, 5, 6]]])

#### np.expand_dims()

In [ ]:
arr = np.array([1, 2, 3])
print(arr[:, np.newaxis])
print(arr[np.newaxis, :])

[[1]
 [2]
 [3]]
[[1 2 3]]


In [ ]:
np.expand_dims(arr, 0)

array([[1, 2, 3]])

In [ ]:
np.expand_dims(arr, 1)

array([[1],
       [2],
       [3]])

In [ ]:
np.expand_dims?

Signature:       np.expand_dims(a, axis)
Call signature:  np.expand_dims(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function expand_dims at 0x0000025FF8D4F1A0>
File:            d:\programdata\anaconda3_240601\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Expand the shape of an array.

Insert a new axis that will appear at the `axis` position in the expanded
array shape.

Parameters
----------
a : array_like
    Input array.
axis : int or tuple of ints
    Position in the expanded axes where the new axis (or axes) is placed.

    .. deprecated:: 1.13.0
        Passing an axis where ``axis > a.ndim`` will be treated as
        ``axis == a.ndim``, and passing ``axis < -a.ndim - 1`` will
        be treated as ``axis == 0``. This behavior is deprecated.

    .. versionchanged:: 1.18.0
        A tuple of axes is now supported.  Out of range axes as
        described above are now forbidden and raise an `AxisError`.

Returns
-------
result : ndar

In [ ]:
# 축 0과 1로 확장
np.expand_dims(arr, axis=(0, 1))

array([[[1, 2, 3]]])

In [ ]:
# 축 0과 1로 확장, 교환법칙 성립
np.expand_dims(arr, axis=(1, 0))

array([[[1, 2, 3]]])

In [ ]:
np.expand_dims(arr, axis=(2, 0))

array([[[1],
        [2],
        [3]]])

In [ ]:
np.expand_dims(arr, axis=(2, 0)).shape

(1, 3, 1)

In [ ]:
np.expand_dims(arr, axis=(2, 1))

array([[[1]],

       [[2]],

       [[3]]])

In [ ]:
np.expand_dims(arr, axis=(2, 1)).shape

(3, 1, 1)

In [ ]:
np.expand_dims(arr, axis=(1, 0))

array([[[1, 2, 3]]])

In [ ]:
np.expand_dims(arr, axis=(0, 1))

array([[[1, 2, 3]]])

In [ ]:
np.expand_dims(np.array([1, 2, 3]), 2)

AxisError: axis 2 is out of bounds for array of dimension 2

#### '0, 3, 0'

https://blog.lockcept.kr/73

### np.r_['0, 3, 0', [1,2,3], [4,5,6]]의 인자 '0, 3, 0'에서 마지막 0
- 1차원을 배열을 3차원으로 확장하는 방법을 기술
    - 지정한 0축을 제외한 축(1, 2 축)으로 확장을 의미

In [ ]:
np.expand_dims(np.array([1,2,3]), axis=(1, 2))

array([[[1]],

       [[2]],

       [[3]]])

In [ ]:
np.expand_dims(np.array([4,5,6]), axis=(1, 2))

array([[[4]],

       [[5]],

       [[6]]])

In [ ]:
np.r_['0, 3, 0', [1,2,3], [4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [ ]:
np.r_['0, 3, 0', [1,2,3], [4,5,6]].shape

(6, 1, 1)

In [ ]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [ ]:
print(np.expand_dims(np.array([1,2,3]), axis=(0, 2)))
print(np.expand_dims(np.array([4,5,6]), axis=(0, 2)))

[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [ ]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]].shape

(2, 3, 1)

In [ ]:
np.r_['0, 3, 2', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
print(np.expand_dims(np.array([1,2,3]), axis=(0, 1)))
print(np.expand_dims(np.array([4,5,6]), axis=(0, 1)))

[[[1 2 3]]]
[[[4 5 6]]]


In [ ]:
np.r_['0, 3, 2', [1,2,3], [4,5,6]].shape

(2, 1, 3)

## 문자열 'r' | 'c': 출력을 변경하는 데 사용
- 문자열 'r' 또는 'c'는 행렬 출력을 생성
- 결과가 1차원이고 'r'이 지정되면 1 x N(행) 행렬이 생성
- 결과가 1차원이고 'c'가 지정되면 N x 1(열) 행렬이 생성
- 결과가 2차원이면 둘 다 동일한 행렬 결과를 제공

In [ ]:
print(np.r_[[1,2,3], [4,5,6]])

# 2차원 매트릭스 생성
np.r_['r', [1,2,3], [4,5,6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [ ]:
print(np.r_[[1,2,3], [4,5,6]])
np.r_['c', [1,2,3], [4,5,6]]

[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
print(np.r_[[[1,2,3]], [[4,5,6]]])

# 2차원 매트릭스 생성
np.r_['r', [[1,2,3]], [[4,5,6]]]

[[1 2 3]
 [4 5 6]]


matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
np.r_['c', [[1,2,3]], [[4,5,6]]]

matrix([[1, 2, 3],
        [4, 5, 6]])

### 1차원 배열의 다양한 결합 방법

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
print(a.shape)
print(b.shape)

(3,)
(3,)


#### 수평 방향으로 쌓기

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 수직 방향으로 쌓기

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_['0, 2', a, b]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

#### 1차원 배열을 열로 바꿔 수평 방향으로 합치는 방법

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.r_['1, 2, 0', a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

## np.concatenate

![image.png](attachment:image.png)

https://leeminki.github.io/edwith/2018/09/26/edwith_python_17.html

In [ ]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
y = np.array([[5, 6]])
y

array([[5, 6]])

In [ ]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
y.T

array([[5],
       [6]])

In [ ]:
np.concatenate((x, y.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
x.flatten()

array([1, 2, 3, 4])

In [ ]:
y.flatten()

array([5, 6])

In [ ]:
np.concatenate((x, y), axis=None)

array([1, 2, 3, 4, 5, 6])

## section 02 배열의 분리

#### (1) 기본 함수 split()

### np.split() 개요

In [ ]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
print(type(s))
print(s[0])

<class 'list'>
[0. 1. 2.]


In [ ]:
np.split(x, 4)

ValueError: array split does not result in an equal division

In [ ]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [ ]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
import numpy as np
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.split(y, [2, 3, 4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [ ]:
np.split(y, [2, 3, 4, 6])


[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int32)]

In [ ]:
y[4:6]

array([50, 60])

In [ ]:
y[6:]

array([], dtype=int32)

#### 다차원 배열 np.hsplit(ary, n)

In [ ]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [ ]:
np.split(a, 5, axis=1)

ValueError: array split does not result in an equal division

In [ ]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [ ]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
np.split(b, [2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int32)]

## (2) 분할 함수 hsplit()과 vsplit()

#### np.hsplit(ary, n)

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.hsplit(a, 3)


[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.hsplit(a, 4)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [ ]:
np.hsplit(a, 5)

ValueError: array split does not result in an equal division

In [ ]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [ ]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

#### np.vsplit()

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.vsplit(a, 2)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [ ]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
np.vsplit(a, 3)


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [ ]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int32)]

In [ ]:
a[:1, :]

array([[0, 1, 2]])

In [ ]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [ ]:
a[6:, :]

array([], shape=(0, 3), dtype=int32)

#### 3차원 배열의 hsplit()

In [ ]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [ ]:
np.split(x, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [ ]:
x[:, :2, :]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]],

       [[24, 25],
        [26, 27]]])

In [ ]:
x[:, 2:, :]

array([[[ 4,  5],
        [ 6,  7]],

       [[12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23]],

       [[28, 29],
        [30, 31]]])

In [ ]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

#### 3차원 배열의 vsplit()

In [ ]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [ ]:
np.split(x, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [ ]:
x[:2, :, :]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [ ]:
x[2:, :, :]

array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [ ]:
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [ ]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

## (3) 정수로 등분 불가능한 분할 함수 array_split()

#### array_split() 개요

In [ ]:
help(np.array_split)

Help on _ArrayFunctionDispatcher in module numpy:

array_split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.

    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.

    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.

    Examples
    --------
    >>> x = np.arange(8.0)
    >>> np.array_split(x, 3)
    [array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]

    >>> x = np.arange(9)
    >>> np.array_split(x, 4)
    [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]



### np.array_split(a, n)
- np.array_split은 원본 배열을 n개의 하위 배열로 나누되, 균등하게 나누어지지 않는 경우에도 가능한 한 균등한 크기로 분할
- 크기가 큰 하위 배열이 먼저 생성되며, 나머지 배열들은 가능한 한 비슷한 크기로 분할
- 크기 (l/n + 1)의 (l % n) 개의 하위 배열을 먼저 생성하고 나머지는 크기 l/n 배열을 생성해 반환

In [ ]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
np.array_split(x, 2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [ ]:
np.split(x, 2)

ValueError: array split does not result in an equal division

In [ ]:
import numpy as np

np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
np.array_split(x, 4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [ ]:
np.array_split(x, 5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [ ]:
np.array_split(x, [2, 4, 8])

[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]

#### 2차원 np.array_split() 분할

In [ ]:
import numpy as np

a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [ ]:
np.array_split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [ ]:
np.array_split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [ ]:
np.array_split(a, 4, axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34]])]

In [ ]:
np.array_split(a, 4, axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27],
        [32]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28],
        [33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [ ]:
np.array_split(a, [2, 4], axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [ ]:
np.array_split(a, [2, 4], axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

## (4) 3차원 이상에서 axis=2로 배열 분할

##### np.array_split(a, axis=2)

In [ ]:
import numpy as np

x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [ ]:
np.array_split(x, 4, axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [ ]:
np.split(x, [2, 4, 5], axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [ ]:
x[:, :, 5:]

array([[[ 5],
        [11]],

       [[17],
        [23]]])

#### numpy.dsplit

In [ ]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [ ]:
np.dsplit(x, 2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [ ]:
np.split(x, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [ ]:
np.array_split(x, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [ ]:
np.dsplit(x, 3)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]

In [ ]:
np.dsplit(x, 4)

ValueError: array split does not result in an equal division

In [ ]:
np.dsplit(x, [2, 4, 5])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [ ]:
x[:, :, 4:5]

array([[[ 4],
        [10]],

       [[16],
        [22]]])

## section 03 numpy의 난수와 다양한 함수

In [ ]:
import numpy as np

rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x1C7AB295FC0

In [ ]:
# Generate one random float uniformly distributed over the range [0, 1)
r = rg.random()
r

0.31675833970975287

In [ ]:
rg.random(5)

array([0.79736546, 0.67625467, 0.39110955, 0.33281393, 0.59830875])

In [ ]:
rg.random((4, 3))

array([[0.18673419, 0.67275604, 0.94180287],
       [0.24824571, 0.94888115, 0.66723745],
       [0.09589794, 0.44183967, 0.88647992],
       [0.6974535 , 0.32647286, 0.73392816]])

In [ ]:
import numpy as np

rg = np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7], dtype=int64)

In [ ]:
rg.integers(1, 7, (3, 4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]], dtype=int64)

In [ ]:
import numpy as np

rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [ ]:
rg.standard_normal((4, 3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])

# end of code