<a href="https://colab.research.google.com/github/soonho123/2026-1-BDA-my-code/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_3%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#빅데이터분석 3주차


In [ ]:
import numpy as np
a = np.power(np.arange(10), 2))\
a


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a[3]

np.int64(9)

In [ ]:
print([-2])

[-2]


In [ ]:
a[-5:-1]

array([25, 36, 49, 64])

In [ ]:
a[-7: -2]

array([ 9, 16, 25, 36, 49])

In [ ]:
a[8:2:-2]

array([64, 36, 16])

In [ ]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a = np.arange(120).reshape(4,5,6)
a

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

In [ ]:
a.reshape(4,5,6)

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

In [ ]:
a[:,2]

array([[ 12,  13,  14,  15,  16,  17],
       [ 42,  43,  44,  45,  46,  47],
       [ 72,  73,  74,  75,  76,  77],
       [102, 103, 104, 105, 106, 107]])

In [ ]:
a[:, 2, 2]

array([ 14,  44,  74, 104])

In [ ]:
a[:, :, 1]

array([[  1,   7,  13,  19,  25],
       [ 31,  37,  43,  49,  55],
       [ 61,  67,  73,  79,  85],
       [ 91,  97, 103, 109, 115]])

In [ ]:
a[...,1]

array([[  1,   7,  13,  19,  25],
       [ 31,  37,  43,  49,  55],
       [ 61,  67,  73,  79,  85],
       [ 91,  97, 103, 109, 115]])

In [ ]:
a[1,...,1]

array([31, 37, 43, 49, 55])

In [ ]:
a[3,...,3]

array([ 93,  99, 105, 111, 117])

In [ ]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

##고급색인

In [ ]:
x = np. arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x = np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [ ]:
x[5,6]

np.int64(46)

In [ ]:
x [ [6,5] ]

array([[48, 49, 50, 51, 52, 53, 54, 55],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x [ [0,1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[1, 1]

np.int64(9)

In [ ]:
x[:, [1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [ ]:
x[:, [2,1]]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

In [ ]:
x[[1,-3], [2,2,3]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [ ]:
x[[1,-3], [2,3]]


array([10, 35])

In [ ]:
x [ [0,2,4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
x[[0,-2,4], 1]

array([ 1, 41, 33])

In [ ]:
a = np.arange(40). reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a [ [2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a [[2,3,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])